# Generated by Django 6.0.1 on 2026-01-28 03:45

import django.db.models.deletion
import gatunki_zagrozone_basenu_morza_srodziemnego.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, validators=[gatunki_zagrozone_basenu_morza_srodziemnego.models.validate_continent_name])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('domain_code', models.CharField(max_length=5)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatunki_zagrozone_basenu_morza_srodziemnego.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(default='N/A', max_length=100, verbose_name='Nazwa polska')),
                ('name_lat', models.CharField(max_length=100, verbose_name='Nazwa łacińska')),
                ('category_ckgz', models.CharField(choices=[('LC', 'LC - Najmniejszej troski'), ('NT', 'NT - Bliskie zagrożenia'), ('VU', 'VU - Narażony'), ('EN', 'EN - Zagrożony'), ('CR', 'CR - Krytycznie zagrożony'), ('EW', 'EW - Wymarły na wolności')], max_length=2, verbose_name='Kategoria CKGZ')),
                ('kingdom', models.CharField(max_length=100, verbose_name='Królestwo')),
                ('phylum', models.CharField(max_length=100, verbose_name='Typ')),
                ('species_class', models.CharField(max_length=100, verbose_name='Gromada')),
                ('order', models.CharField(max_length=100, verbose_name='Rząd')),
                ('family', models.CharField(max_length=100, verbose_name='Rodzina')),
                ('genus', models.CharField(max_length=100, verbose_name='Rodzaj')),
                ('protection_actions', models.BooleanField(default=False, verbose_name='Działania prowadzone?')),
                ('protection_intensity', models.CharField(blank=True, choices=[('low', 'Niska'), ('medium', 'Średnia'), ('high', 'Wysoka')], max_length=10, null=True)),
                ('protection_organizations', models.TextField(blank=True, null=True, verbose_name='Organizacje')),
                ('is_endemic', models.CharField(choices=[('tak', 'Endemit'), ('nie', 'Gatunek o dużej powierzchni występowania')], default='nie', max_length=3)),
                ('is_mainstream', models.CharField(choices=[('tak', 'Gatunek mainstreamowy'), ('nie', 'Gatunek nieznany szerszej publice')], default='nie', max_length=3)),
                ('description', models.TextField(verbose_name='Opis')),
                ('appearance', models.TextField(verbose_name='Wygląd')),
                ('habitat_and_diet', models.TextField(verbose_name='Habitat i dieta')),
                ('countries', models.ManyToManyField(to='gatunki_zagrozone_basenu_morza_srodziemnego.country', verbose_name='Kraje występowania')),
            ],
        ),
    ]
