# Generated by Django 6.0.1 on 2026-01-29 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatunki_zagrozone_basenu_morza_srodziemnego', '0002_species_author_species_created_at_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wiek',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Dziwne'), django.core.validators.MaxValueValidator(99, message='Nie sądzę ,że jesteś aż tak stary')]),
        ),
    ]
